version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  # build:
  #   working_directory: ~/repo
  #   docker:
  #     - image: circleci/node:12
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      # - run:
      #   name: Update Yarn
      #   command: "sudo yarn add yarn -g"
      # - restore_cache:
      #   key: dependency-cache-{{ checksum "yarn.lock" }}
      # - run:
      #   name: Install Dependencies
      #   command: yarn install
      # - save_cache:
      #   key: dependency-cache-{{ checksum "yarn.lock" }}
      #   paths:
      #     - ./node_modules
      - run:
        command: yarn test
        name: Run tests
      - run:
        command: yarn build
        name: Build app
      - persist_to_workspace:
        root: ~/project
      paths:
        - .
        